### ISSUE TITLE
[BUG] Error reported when calling ZhipuAiChatModel

### ISSUE THREAD

**Issue by cv-msan** [langchain4j/langchain4j-community#40]
## Describe the bug

Calling reports an error and returns an error message 
```
callTimeout cannot be null
2024-12-26 08:43:35.640 ERROR 2700 --- [  XNIO-1 task-2] com.tyer.ai.rag.config.ChatService       : Please specify either chatLanguageModel or streamingChatLanguageModel
```
## Minimal Example to Reproduce

```
public interface ChatModelFactory {
  
    ChatLanguageModel createModel();
}
public class ZhipuChatModelFactory implements ChatModelFactory {
    @Override
    public ChatLanguageModel createModel() {
  
        String apiKey = xxxx;
        String modelName = glm-4-plus;
        String baseUrl = ”https://open.bigmodel.cn/api/paas/v4“;
        // 返回 Zhipu 模型实例
        return ZhipuAiChatModel.builder().temperature(0.2).topP(0.3)
                .apiKey(apiKey)
                .model(modelName)
                .baseUrl(baseUrl)
                .build();
    }
}
public ChatAssistant appAssistant(AppMessageVo message) {
                    return AiServices.builder(ChatAssistant.class)
                            .chatMemoryProvider(buildMemoryProvider()) // 设置历史对话窗口
                            .chatLanguageModel(languageModel) // 配置语言模型
                            .build();
    }
ChatAssistant chatAssistant = chatService.appAssistant(messageVo);
Result<String> resultChat = chatAssistant.chat(sessionId, messageVo.getMessage());
```

## Please complete the following information:
- LangChain4j Community version:1.0.0
- LangChain4j Community Component you used (e.g. `langchain4j-community-zhipu-ai`):
- Java version: 17
- Spring Boot version (if applicable): 3

## Additional context

Because the official website documentation is not very complete at present, and the example codes are all invalid, I cannot investigate the problem well. I have tried to remove the baseURL (because QwenChatModel only needs to remove the baseURL), but it still does not work properly,

**Comment by Martin7-1** [comment]
@cv-msan Thank you for reporting!

The error is because you do not specify the `callTimeout`, maybe we should give a default value to it. The following code should work fine:

```java
    ZhipuAiChatModel chatModel = ZhipuAiChatModel.builder()
            .apiKey(apiKey)
            .logRequests(true)
            .logResponses(true)
            .maxRetries(1)
            .callTimeout(Duration.ofSeconds(60))
            .connectTimeout(Duration.ofSeconds(60))
            .writeTimeout(Duration.ofSeconds(60))
            .readTimeout(Duration.ofSeconds(60))
            .build();
```

I will add the document asap. You can refer to [ZhipuAiChatModelIT](https://github.com/langchain4j/langchain4j-community/blob/main/models/langchain4j-community-zhipu-ai/src/test/java/dev/langchain4j/community/model/zhipu/ZhipuAiChatModelIT.java) for now.

**Comment by cv-msan** [comment]
Do I not need to specify baseURL when building with a dedicated model?

**Comment by Martin7-1** [comment]
Actually not, `ZhipuAiChatModel` will use default value (`"https://open.bigmodel.cn/"`) for `baseUrl` if you do not specify it.

**Comment by cv-msan** [comment]
So these exclusive baseURLs all have default values, right？

**Comment by Martin7-1** [comment]
You can check [ZhipuAiChatModel constructor](https://github.com/langchain4j/langchain4j-community/blob/34577ce9d738ab9e30273d8b44966c34bafa9c38/models/langchain4j-community-zhipu-ai/src/main/java/dev/langchain4j/community/model/zhipu/ZhipuAiChatModel.java#L62) and [ZhipuAiClient](https://github.com/langchain4j/langchain4j-community/blob/34577ce9d738ab9e30273d8b44966c34bafa9c38/models/langchain4j-community-zhipu-ai/src/main/java/dev/langchain4j/community/model/zhipu/ZhipuAiClient.java#L56) for more details about deafult value.

BTW, do you think we should add about which parameter is optional in the document? Looking forward to your feedback about which content do you want to see in the document.

**Comment by cv-msan** [comment]
Yes, I think good document content should include a specific list of parameters and whether they are mandatory, and then add annotated example code

**Comment by Martin7-1** [comment]
Thank you for your feedback! We will improve our documents about `langchain4j-community-dashscope` and `langchain4j-community-zhipuai` asap.
