### ISSUE TITLE
[FEATURE] SearXNG Support

### ISSUE THREAD

**Issue by bnayfeh** [langchain4j/langchain4j-community#7]
## Is your feature request related to a problem? Please describe.

SearXNG is a popular search engine aggregator that provides API access and is supported by the Langchain project but not Langchain4j

## Describe the solution you'd like

An implementation of web-search-engine that supports SearXNG similar to the current support for Google, Tavily and Search API

## Describe alternatives you've considered

None

## Additional context

None

**Comment by Martin7-1** [comment]
@bnayfeh Hi! Thank you for your contribution. Noted that in `langchain4j-community`, the package name should be `dev.langchain4j.community.xxx.xxx`, and we do not want to introduce `lombok` in new integration :)
